version: "3"
services:
  warp_socks:
    image: weycovo/docker-warp_socks:latest
    restart: unless-stopped
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    cap_add:
      - NET_ADMIN
    volumes:
      - ./wgcf:/wgcf